/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge.vue')['default']
    Button: typeof import('./src/components/ui/button.vue')['default']
    Card: typeof import('./src/components/ui/card.vue')['default']
    CardContent: typeof import('./src/components/ui/card-content.vue')['default']
    CardHeader: typeof import('./src/components/ui/card-header.vue')['default']
    CardTitle: typeof import('./src/components/ui/card-title.vue')['default']
    Checkbox: typeof import('./src/components/ui/checkbox.vue')['default']
    ContractUnderstanding: typeof import('./src/components/contracts/ContractUnderstanding.vue')['default']
    ContractUnderstandingOld: typeof import('./src/components/ContractUnderstanding-old.vue')['default']
    DemoReportCard: typeof import('./src/components/demo/DemoReportCard.vue')['default']
    DemoRiskClause: typeof import('./src/components/demo/DemoRiskClause.vue')['default']
    DemoStepCard: typeof import('./src/components/demo/DemoStepCard.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog.vue')['default']
    HighlightedPdfViewer: typeof import('./src/components/HighlightedPdfViewer.vue')['default']
    Input: typeof import('./src/components/ui/input.vue')['default']
    Label: typeof import('./src/components/ui/label.vue')['default']
    Modal: typeof import('./src/components/ui/modal.vue')['default']
    PdfViewer: typeof import('./src/components/PdfViewer.vue')['default']
    Progress: typeof import('./src/components/ui/progress.vue')['default']
    ReviewConfig: typeof import('./src/components/review/ReviewConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleJudgment: typeof import('./src/components/review/RuleJudgment.vue')['default']
    Select: typeof import('./src/components/ui/select.vue')['default']
    SelectItem: typeof import('./src/components/ui/select-item.vue')['default']
    Separator: typeof import('./src/components/ui/separator.vue')['default']
    Tabs: typeof import('./src/components/ui/tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/tabs-content.vue')['default']
    TabsList: typeof import('./src/components/ui/tabs-list.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/tabs-trigger.vue')['default']
    Toast: typeof import('./src/components/ui/toast.vue')['default']
    ToastProvider: typeof import('./src/components/ui/toast-provider.vue')['default']
    WordSuggestionCard: typeof import('./src/components/WordSuggestionCard.vue')['default']
  }
}
